### ISSUE TITLE
Unable to install required gem

### ISSUE THREAD

**Issue by tchncs** [whitekiba/irc-jabber-mumble-bridge#5]
Hi, im [unable to install](https://github.com/jeffpeterson/irc/issues/3) the gem `irc`.

```
Makefile:238: recipe for target 'posix_serialport_impl.o' failed
```

Im new to ruby - is there any alternative gem out there?

**Comment by whitekiba** [comment]
That it most likely related to incompatible packages on your system.
We are using rvm (http://rvm.io/) to manage the runtime for our ruby applications. Currently we are developing on Ruby 2.2.4
